[tool.poetry]
name = "find-net-board"
version = "0.1.0"
description = ""
authors = ["Vasilis Petrakopoulos <vasilis4998@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
mysql-connector-python = "^8.3.0"
alive-progress = "^3.1.5"
django = "^5.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
