# Generated by Django 5.0.4 on 2024-05-20 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_consistency_eida_routing_fdsn_registry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consistency',
            name='eidarout_net',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.eida_routing'),
        ),
        migrations.AlterField(
            model_name='consistency',
            name='fdsn_net',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.fdsn_registry'),
        ),
        migrations.AlterField(
            model_name='consistency',
            name='xml_net',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.stationxml'),
        ),
    ]
